

// صفحه تکمیل خرید و پرداخت







import { Grid, Typography, TextField, Button } from '@material-ui/core'
import React, { useContext, useRef, useEffect, useState } from 'react'
import useStyles from './completeOrder.styles'
import Location from '../../assets/images/home.svg'
import Card from '../../assets/images/card.svg'
import Radio from '@material-ui/core/Radio'
import RadioGroup from '@material-ui/core/RadioGroup'
import FormControlLabel from '@material-ui/core/FormControlLabel'
import FormControl from '@material-ui/core/FormControl'
import { CartContext } from '../../contexts/CartContext'
import axios from 'axios'
import Autocomplete from '@material-ui/lab/Autocomplete'

export default function CompleteOrder() {




    const classes = useStyles()
    const { cartData, totalPrice, Basket, totalWtakhfif, OText } = useContext(CartContext)
    const [choiceValue, choiceSetValue] = useState('پرداخت اینترنتی')

    const handleChange = (event) => {
        choiceSetValue(event.target.value)
    }

    const defaultProps = {
        options: ostan.map((option) => option.value),

        getOptionLabel: (option) => option,
    }

    // const flatProps = {
    //     options: ostan.map(('')),
    //     options: shahr.map(('')),
    // }

    const [ostanValue, ostanSetValue] = useState('')
    const [shahrValue, shahrSetValue] = useState('')


    const defaultPropsS = {
        options: shahr.map((option) => option.value),

        getOptionLabel: (option) => option,
    }



    async function submit() {
        try {

            const name = document.querySelector("#name").value
            const phone = document.querySelector("#phone").value
            // const ostan = ostanValue
            // const shahr = shahrValue
            const addres = document.querySelector("#addres").value
            const basket = JSON.stringify(Basket)
            const payChoice = choiceValue
            const takhfifCode = localStorage.getItem('takhfifCode')
            const takhfifAmount = localStorage.getItem('takhfifAmount')
            const amount = totalPrice(cartData) + OText().price



            console.log(amount);



            const formData = new FormData()
            formData.append("name", name)
            formData.append("phone", phone)
            formData.append("takhfifCode", takhfifCode)
            formData.append("takhfifAmount", takhfifAmount)
            formData.append("addres", addres)
            formData.append('basket', basket)


            formData.append("payChoice", payChoice)
            // formData.append("orderCode", orderCode)
            formData.append("amount", amount)
            // formData.append("postalCode", postalCode)



            await axios.post("https://api.balamala.ir/order", formData)


                .then(res => {

                    const ccOrder = res.data

                    if (payChoice === 'پرداخت اینترنتی') {



                        axios.get("https://api.balamala.ir/checkoutBasket", {
                            params: {
                                CCOrder: ccOrder

                            }
                        })
                            .then(res => {
                                if (res.data.err === true) {
                                    alert('مشکلی در ارتباط با سرور به وجود آمده است لطفا دوباره تلاش کنید')
                                }
                                else {

                                    window.location.assign(res.data.Url)

                                }





                            }).catch(err => {
                                console.log(err)

                            })

                    }
                    else {
                        axios.get("https://api.balamala.ir/cartToCart", {
                            params: {
                                CCOrder: ccOrder
                            }
                        })
                            .then(res => {

                                window.location.assign(`https://balamala.ir/resultPay?paymentCode=${res.data.paymentCode}`, {
                                    params: {
                                        cartData: cartData
                                    }
                                })
                                localStorage.removeItem('cartData')
                            }).catch(err => {
                                console.log(err)
                                alert('متاسفانه مشکل در ارتباط با سرور پیدا شده،دوباره امتحان کنید')
                            })
                    }
                })
                .catch(err => {
                    console.log(err)
                    alert('فیلد ها را کامل پر کنید و دوباره امتحان کنید.')

                })

        }



        catch (err) {
            console.log(err)
        }
    }


    // console.log(cartData.map((item) => item.pushC))


    return (
        <Grid className={classes.root} container >


            <Grid className={classes.addres}>
                <img alt='آدرس(رابین پوش)' className={classes.image} src={Location} ></img>
                <TextField className={classes.fieldInput} id="name" label=' نام و نام خانوادگی تحویل گیرنده:' fullWidth  ></TextField>
                <TextField className={classes.fieldInput} placeholder='به زبان انگلیسی(لاتین)' lang='en' type='number' id="phone" label='شماره همراه(الزامی می باشد):' fullWidth  ></TextField>

                {/* <div className={classes.inputDiv} >
                    <Autocomplete className={classes.OstanInput}
                        {...defaultProps}
                        id="ostan"
                        value={ostanValue}
                        onChange={(event, newValue) => {
                            ostanSetValue(newValue)
                        }}
                        renderInput={(params) => <TextField {...params} className={classes.fieldInput} label="استان " margin="normal" />}
                    />
                    <Autocomplete className={classes.ShahrInput}
                        {...defaultPropsS}
                        id="shahr"
                        value={shahrValue}
                        onChange={(event, newValue) => {
                            shahrSetValue(newValue)
                        }}
                        renderInput={(params) => <TextField className={classes.fieldInput} {...params} label="شهر" margin="normal" />}
                    />

                </div> */}

                {/* <TextField className={classes.fieldInput} id="postalCode" label=' کدپستی:' fullWidth > <Button size='small' variant='contained' color='primary' className={classes.Button2} href='https://epostcode.post.ir/codefinder' > دریافت کد پستی</Button></TextField> */}


                <TextField className={classes.fieldInput2} id="addres" label=' آدرس پستی:' fullWidth  ></TextField>
                <div className={classes.typoF}>
                    <Typography variant='h5' className={classes.Utypo}>*فیلد ها را با دقت پر کنید*</Typography>
                    <Typography variant='h5' className={classes.Utypo}>*شماره همراه الزامی می باشد*</Typography>


                </div>
            </Grid>
            <Grid className={classes.pay} >
                <img alt='پرداخت' className={classes.image} src={Card} ></img>


                <FormControl component="fieldset" className={classes.form}>

                    <RadioGroup
                        aria-label="gender"
                        name="controlled-radio-buttons-group"
                        value={choiceValue}
                        onChange={handleChange}
                        id="payChoice"
                        className={classes.form}

                    >
                        <FormControlLabel value="پرداخت اینترنتی" control={<Radio style={{ backgroundColor: 'rgb(162 233 255)', marginLeft: 9, display: 'flex' }} color='primary' />} label="پرداخت اینترنتی" />
                        <FormControlLabel value="پرداخت درب محل" control={<Radio style={{ backgroundColor: 'rgb(162 233 255)', marginLeft: 9, display: 'flex' }} color='primary' />} label="پرداخت در محل" />
                    </RadioGroup>
                </FormControl>

                <Typography className={classes.text} >برای پرداخت کارت به کارت پس از ثبت سفارش تا یک روز کاری پس از ثبت سفارش مبلغ سفارش را به شماره حساب 6280231339960279 واریز نمایید و رسید آن را به واتساپ شماره 09182144970 ارسال نمایید تا سفارش شما نهایی شود.</Typography>

            </Grid>

            <div className={classes.ButtonDiv}>
                <Button onClick={submit} size='large' variant='contained' color='primary' className={classes.Button} > تکمیل خرید</Button>
                <Button size='large' variant='contained' color='primary' className={classes.Button} href='https://epostcode.post.ir/codefinder' > دریافت کد پستی</Button>
            </div>

        </Grid >





    )
}
const ostan = [

    { value: 'آذربایجان شرقی', ostanId: 1 },
    { value: 'آذربایجان غربی', ostanId: 2 },
    { value: 'اردبیل', ostanId: 3 },
    { value: 'اصفهان', ostanId: 4 },
    { value: 'البرز', ostanId: 5 },
    { value: 'ایلام', ostanId: 6 },
    { value: 'بوشهر', ostanId: 7 },
    { value: 'تهران', ostanId: 8 },
    { value: 'چهارمحال و بختیاری', ostanId: 9 },
    { value: 'خراسان جنوبی', ostanId: 10 },
    { value: 'خراسان رضوی', ostanId: 11 },
    { value: 'خراسان شمالی', ostanId: 12 },
    { value: 'خوزستان', ostanId: 13 },
    { value: 'زنجان', ostanId: 14 },
    { value: 'سمنان', ostanId: 15 },
    { value: 'سیستان و بلوچستان', ostanId: 16 },
    { value: 'فارس', ostanId: 17 },
    { value: 'قزوین', ostanId: 18 },
    { value: 'قم', ostanId: 19 },
    { value: 'کردستان', ostanId: 20 },
    { value: 'کرمانشاه', ostanId: 21 },
    { value: 'کرمان', ostanId: 22 },
    { value: 'کهکیلویه و بویراحمد', ostanId: 23 },
    { value: 'گلستان', ostanId: 24 },
    { value: 'گیلان', ostanId: 25 },
    { value: 'لرستان', ostanId: 26 },
    { value: 'مازندران', ostanId: 27 },
    { value: 'هرمزگان', ostanId: 28 },
    { value: 'مرکزی', ostanId: 29 },
    { value: 'همدان', ostanId: 30 },
    { value: 'یزد', ostanId: 31 },
]

const
    shahr = [

        { value: 'کشکسرای', ostanId: 1 },
        { value: 'سهند', ostanId: 1 },
        { value: 'سیس', ostanId: 1 },
        { value: 'دوزدوزان', ostanId: 1 },
        { value: 'تیمورلو', ostanId: 1 },
        { value: 'صوفیان', ostanId: 1 },
        { value: 'سردرود', ostanId: 1 },
        { value: 'هادیشهر', ostanId: 1 },
        { value: 'هشترود', ostanId: 1 },
        { value: 'زرنق', ostanId: 1 },
        { value: 'ترکمانچای', ostanId: 1 },
        { value: 'ورزقان', ostanId: 1 },
        { value: 'تسوج', ostanId: 1 },
        { value: 'زنوز', ostanId: 1 },
        { value: 'ایلخچی', ostanId: 1 },
        { value: 'شرفخانه', ostanId: 1 },
        { value: 'مهربان', ostanId: 1 },
        { value: 'مبارک شهر', ostanId: 1 },
        { value: 'تیکمه داش', ostanId: 1 },
        { value: 'باسمنج', ostanId: 1 },
        { value: 'سیه رود', ostanId: 1 },
        { value: 'میانه', ostanId: 1 },
        { value: 'خمارلو', ostanId: 1 },
        { value: 'خواجه', ostanId: 1 },
        { value: 'بناب مرند', ostanId: 1 },
        { value: 'قره آغاج', ostanId: 1 },
        { value: 'وایقان', ostanId: 1 },
        { value: 'مراغه', ostanId: 1 },
        { value: 'ممقان', ostanId: 1 },
        { value: 'خامنه', ostanId: 1 },
        { value: 'خسروشاه', ostanId: 1 },
        { value: 'لیلان', ostanId: 1 },
        { value: 'نظرکهریزی', ostanId: 1 },
        { value: 'اهر', ostanId: 1 },
        { value: 'بخشایش', ostanId: 1 },
        { value: 'آقکند', ostanId: 1 },
        { value: 'جوان قلعه', ostanId: 1 },
        { value: 'کلیبر', ostanId: 1 },
        { value: 'مرند', ostanId: 1 },
        { value: 'اسکو', ostanId: 1 },
        { value: 'شندآباد', ostanId: 1 },
        { value: 'شربیان', ostanId: 1 },
        { value: 'گوگان', ostanId: 1 },
        { value: 'بستان آباد', ostanId: 1 },
        { value: 'تبریز', ostanId: 1 },
        { value: 'جلفا', ostanId: 1 },
        { value: 'اچاچی', ostanId: 1 },
        { value: 'هریس', ostanId: 1 },
        { value: 'یامچی', ostanId: 1 },
        { value: 'خاروانا', ostanId: 1 },
        { value: 'کوزه کنان', ostanId: 1 },
        { value: 'خداجو(خراجو)', ostanId: 1 },
        { value: 'آذرشهر', ostanId: 1 },
        { value: 'شبستر', ostanId: 1 },
        { value: 'سراب', ostanId: 1 },
        { value: 'ملکان', ostanId: 1 },
        { value: 'بناب', ostanId: 1 },
        { value: 'هوراند', ostanId: 1 },
        { value: 'کلوانق', ostanId: 1 },
        { value: 'ترک', ostanId: 1 },
        { value: 'عجب شیر', ostanId: 1 },
        { value: 'آبش احمد', ostanId: 1 },
        { value: 'تازه شهر', ostanId: 2 },
        { value: 'نالوس', ostanId: 2 },
        { value: 'ایواوغلی', ostanId: 2 },
        { value: 'شاهین دژ', ostanId: 2 },
        { value: 'گردکشانه', ostanId: 2 },
        { value: 'باروق', ostanId: 2 },
        { value: 'سیلوانه', ostanId: 2 },
        { value: 'بازرگان', ostanId: 2 },
        { value: 'نازک علیا', ostanId: 2 },
        { value: 'ربط', ostanId: 2 },
        { value: 'تکاب', ostanId: 2 },
        { value: 'دیزج دیز', ostanId: 2 },
        { value: 'سیمینه', ostanId: 2 },
        { value: 'نوشین', ostanId: 2 },
        { value: 'میاندوآب', ostanId: 2 },
        { value: 'مرگنلر', ostanId: 2 },
        { value: 'سلماس', ostanId: 2 },
        { value: 'آواجیق', ostanId: 2 },
        { value: 'قطور', ostanId: 2 },
        { value: 'محمودآباد', ostanId: 2 },
        { value: 'خوی', ostanId: 2 },
        { value: 'نقده', ostanId: 2 },
        { value: 'سرو', ostanId: 2 },
        { value: 'خلیفان', ostanId: 2 },
        { value: 'پلدشت', ostanId: 2 },
        { value: 'میرآباد', ostanId: 2 },
        { value: 'اشنویه', ostanId: 2 },
        { value: 'زرآباد', ostanId: 2 },
        { value: 'بوکان', ostanId: 2 },
        { value: 'پیرانشهر', ostanId: 2 },
        { value: 'چهاربرج', ostanId: 2 },
        { value: 'قوشچی', ostanId: 2 },
        { value: 'شوط', ostanId: 2 },
        { value: 'ماکو', ostanId: 2 },
        { value: 'سیه چشمه', ostanId: 2 },
        { value: 'سردشت', ostanId: 2 },
        { value: 'کشاورز', ostanId: 2 },
        { value: 'فیرورق', ostanId: 2 },
        { value: 'محمدیار', ostanId: 2 },
        { value: 'ارومیه', ostanId: 2 },
        { value: 'مهاباد', ostanId: 2 },
        { value: 'قره ضیاءالدین', ostanId: 2 },
        { value: 'پارس آباد', ostanId: 3 },
        { value: 'فخراباد', ostanId: 3 },
        { value: 'کلور', ostanId: 3 },
        { value: 'نیر', ostanId: 3 },
        { value: 'اردبیل', ostanId: 3 },
        { value: 'اسلام اباد', ostanId: 3 },
        { value: 'تازه کندانگوت', ostanId: 3 },
        { value: 'مشگین شهر', ostanId: 3 },
        { value: 'جعفرآباد', ostanId: 3 },
        { value: 'نمین', ostanId: 3 },
        { value: 'اصلاندوز', ostanId: 3 },
        { value: 'مرادلو', ostanId: 3 },
        { value: 'خلخال', ostanId: 3 },
        { value: 'کوراییم', ostanId: 3 },
        { value: 'هیر', ostanId: 3 },
        { value: 'گیوی', ostanId: 3 },
        { value: 'گرمی', ostanId: 3 },
        { value: 'لاهرود', ostanId: 3 },
        { value: 'هشتجین', ostanId: 3 },
        { value: 'عنبران', ostanId: 3 },
        { value: 'تازه کند', ostanId: 3 },
        { value: 'قصابه', ostanId: 3 },
        { value: 'رضی', ostanId: 3 },
        { value: 'سرعین', ostanId: 3 },
        { value: 'بیله سوار', ostanId: 3 },
        { value: 'آبی بیگلو', ostanId: 3 },
        { value: 'گزبرخوار', ostanId: 4 },
        { value: 'زیار', ostanId: 4 },
        { value: 'زرین شهر', ostanId: 4 },
        { value: 'گلشن', ostanId: 4 },
        { value: 'پیربکران', ostanId: 4 },
        { value: 'خالدآباد', ostanId: 4 },
        { value: 'سجزی', ostanId: 4 },
        { value: 'گوگد', ostanId: 4 },
        { value: 'تیران', ostanId: 4 },
        { value: 'ونک', ostanId: 4 },
        { value: 'دهق', ostanId: 4 },
        { value: 'زواره', ostanId: 4 },
        { value: 'کاشان', ostanId: 4 },
        { value: 'ابوزیدآباد', ostanId: 4 },
        { value: 'اصغرآباد', ostanId: 4 },
        { value: 'بافران', ostanId: 4 },
        { value: 'شهرضا', ostanId: 4 },
        { value: 'خور', ostanId: 4 },
        { value: 'مجلسی', ostanId: 4 },
        { value: 'هرند', ostanId: 4 },
        { value: 'فولادشهر', ostanId: 4 },
        { value: 'کمشچه', ostanId: 4 },
        { value: 'کلیشادوسودرجان', ostanId: 4 },
        { value: 'لای بید', ostanId: 4 },
        { value: 'قهجاورستان', ostanId: 4 },
        { value: 'چرمهین', ostanId: 4 },
        { value: 'رزوه', ostanId: 4 },
        { value: 'فریدونشهر', ostanId: 4 },
        { value: 'طرق رود', ostanId: 4 },
        { value: 'نصرآباد', ostanId: 4 },
        { value: 'برزک', ostanId: 4 },
        { value: 'سفیدشهر', ostanId: 4 },
        { value: 'سمیرم', ostanId: 4 },
        { value: 'گلدشت', ostanId: 4 },
        { value: 'اردستان', ostanId: 4 },
        { value: 'جوشقان قالی', ostanId: 4 },
        { value: 'بویین ومیاندشت', ostanId: 4 },
        { value: 'کرکوند', ostanId: 4 },
        { value: 'درچه', ostanId: 4 },
        { value: 'انارک', ostanId: 4 },
        { value: 'دولت آباد', ostanId: 4 },
        { value: 'ایمانشهر', ostanId: 4 },
        { value: 'گرگاب', ostanId: 4 },
        { value: 'حسن اباد', ostanId: 4 },
        { value: 'سده لنجان', ostanId: 4 },
        { value: 'حبیب آباد', ostanId: 4 },
        { value: 'بهاران شهر', ostanId: 4 },
        { value: 'میمه', ostanId: 4 },
        { value: 'تودشک', ostanId: 4 },
        { value: 'گلشهر', ostanId: 4 },
        { value: 'رضوانشهر', ostanId: 4 },
        { value: 'داران', ostanId: 4 },
        { value: 'علویجه', ostanId: 4 },
        { value: 'نیک آباد', ostanId: 4 },
        { value: 'مشکات', ostanId: 4 },
        { value: 'آران وبیدگل', ostanId: 4 },
        { value: 'خوانسار', ostanId: 4 },
        { value: 'نجف آباد', ostanId: 4 },
        { value: 'منظریه', ostanId: 4 },
        { value: 'فرخی', ostanId: 4 },
        { value: 'دیزیچه', ostanId: 4 },
        { value: 'اژیه', ostanId: 4 },
        { value: 'زاینده رود', ostanId: 4 },
        { value: 'خورزوق', ostanId: 4 },
        { value: 'قهدریجان', ostanId: 4 },
        { value: 'شاهین شهر', ostanId: 4 },
        { value: 'بهارستان', ostanId: 4 },
        { value: 'چمگردان', ostanId: 4 },
        { value: 'دهاقان', ostanId: 4 },
        { value: 'برف انبار', ostanId: 4 },
        { value: 'بادرود', ostanId: 4 },
        { value: 'کوهپایه', ostanId: 4 },
        { value: 'گلپایگان', ostanId: 4 },
        { value: 'عسگران', ostanId: 4 },
        { value: 'حنا', ostanId: 4 },
        { value: 'کهریزسنگ', ostanId: 4 },
        { value: 'مهاباد', ostanId: 4 },
        { value: 'کامو و چوگان', ostanId: 4 },
        { value: 'افوس', ostanId: 4 },
        { value: 'زیباشهر', ostanId: 4 },
        { value: 'کوشک', ostanId: 4 },
        { value: 'نایین', ostanId: 4 },
        { value: 'سین', ostanId: 4 },
        { value: 'زازران', ostanId: 4 },
        { value: 'مبارکه', ostanId: 4 },
        { value: 'ورزنه', ostanId: 4 },
        { value: 'ورنامخواست', ostanId: 4 },
        { value: 'شاپورآباد', ostanId: 4 },
        { value: 'فلاورجان', ostanId: 4 },
        { value: 'وزوان', ostanId: 4 },
        { value: 'اصفهان', ostanId: 4 },
        { value: 'باغ بهادران', ostanId: 4 },
        { value: 'باغ بهادران', ostanId: 4 },
        { value: 'دامنه', ostanId: 4 },
        { value: 'نطنز', ostanId: 4 },
        { value: 'محمدآباد', ostanId: 4 },
        { value: 'نیاسر', ostanId: 4 },
        { value: 'نوش آباد ', ostanId: 4 },
        { value: 'کمه', ostanId: 4 },
        { value: 'جوزدان', ostanId: 4 },
        { value: 'قمصر', ostanId: 4 },
        { value: 'جندق', ostanId: 4 },
        { value: 'طالخونچه', ostanId: 4 },
        { value: 'خمینی شهر', ostanId: 4 },
        { value: 'باغشاد', ostanId: 4 },
        { value: 'دستگرد', ostanId: 4 },
        { value: 'ابریشم', ostanId: 4 },
        { value: 'چهارباغ', ostanId: 5 },
        { value: 'آسارا', ostanId: 5 },
        { value: 'کرج', ostanId: 5 },
        { value: 'طالقان', ostanId: 5 },
        { value: 'هشتگرد', ostanId: 5 },
        { value: 'محمدشهر', ostanId: 5 },
        { value: 'مشکین دشت', ostanId: 5 },
        { value: 'نظرآباد', ostanId: 5 },
        { value: 'هشتگرد', ostanId: 5 },
        { value: 'ماهدشت', ostanId: 5 },
        { value: 'اشتهارد', ostanId: 5 },
        { value: 'کوهسار', ostanId: 5 },
        { value: 'گرمدره', ostanId: 5 },
        { value: 'تنکمان', ostanId: 5 },
        { value: 'گلسار', ostanId: 5 },
        { value: 'کمال شهر', ostanId: 5 },
        { value: 'فردیس', ostanId: 5 },
        { value: 'آبدانان', ostanId: 6 },
        { value: 'شباب', ostanId: 6 },
        { value: 'موسیان', ostanId: 6 },
        { value: 'بدره', ostanId: 6 },
        { value: 'ایلام', ostanId: 6 },
        { value: 'ایوان', ostanId: 6 },
        { value: 'مهران', ostanId: 6 },
        { value: 'آسمان آباد', ostanId: 6 },
        { value: 'پهله', ostanId: 6 },
        { value: 'مهر', ostanId: 6 },
        { value: 'سراب باغ', ostanId: 6 },
        { value: 'بلاوه', ostanId: 6 },
        { value: 'میمه', ostanId: 6 },
        { value: 'دره شهر', ostanId: 6 },
        { value: 'ارکواز', ostanId: 6 },
        { value: 'مورموری', ostanId: 6 },
        { value: 'توحید', ostanId: 6 },
        { value: 'دهلران', ostanId: 6 },
        { value: 'لومار', ostanId: 6 },
        { value: 'چوار', ostanId: 6 },
        { value: 'زرنه', ostanId: 6 },
        { value: 'صالح آباد', ostanId: 6 },
        { value: 'سرابله', ostanId: 6 },
        { value: 'ماژین', ostanId: 6 },
        { value: 'دلگشا', ostanId: 6 },
        { value: 'کرمانشاه', ostanId: 6 },
        { value: 'لای بید', ostanId: 4 },
        { value: 'قهجاورستان', ostanId: 4 },
        { value: 'چرمهین', ostanId: 4 },
        { value: 'رزوه', ostanId: 4 },
        { value: 'فریدونشهر', ostanId: 4 },
        { value: 'طرق رود', ostanId: 4 },
        { value: 'نصرآباد', ostanId: 4 },
        { value: 'برزک', ostanId: 4 },
        { value: 'سفیدشهر', ostanId: 4 },
        { value: 'سمیرم', ostanId: 4 },
        { value: 'گلدشت', ostanId: 4 },
        { value: 'اردستان', ostanId: 4 },
        { value: 'جوشقان قالی', ostanId: 4 },
        { value: 'بویین ومیاندشت', ostanId: 4 },
        { value: 'کرکوند', ostanId: 4 },
        { value: 'درچه', ostanId: 4 },
        { value: 'انارک', ostanId: 4 },
        { value: 'دولت آباد', ostanId: 4 },
        { value: 'ایمانشهر', ostanId: 4 },
        { value: 'گرگاب', ostanId: 4 },
        { value: 'حسن اباد', ostanId: 4 },
        { value: 'سده لنجان', ostanId: 4 },
        { value: 'حبیب آباد', ostanId: 4 },
        { value: 'بهاران شهر', ostanId: 4 },
        { value: 'میمه', ostanId: 4 },
        { value: 'تودشک', ostanId: 4 },
        { value: 'گلشهر', ostanId: 4 },
        { value: 'رضوانشهر', ostanId: 4 },
        { value: 'داران', ostanId: 4 },
        { value: 'علویجه', ostanId: 4 },
        { value: 'نیک آباد', ostanId: 4 },
        { value: 'مشکات', ostanId: 4 },
        { value: 'آران وبیدگل', ostanId: 4 },
        { value: 'خوانسار', ostanId: 4 },
        { value: 'نجف آباد', ostanId: 4 },
        { value: 'منظریه', ostanId: 4 },
        { value: 'فرخی', ostanId: 4 },
        { value: 'دیزیچه', ostanId: 4 },
        { value: 'اژیه', ostanId: 4 },
        { value: 'زاینده رود', ostanId: 4 },
        { value: 'خورزوق', ostanId: 4 },
        { value: 'قهدریجان', ostanId: 4 },
        { value: 'شاهین شهر', ostanId: 4 },
        { value: 'بهارستان', ostanId: 4 },
        { value: 'چمگردان', ostanId: 4 },
        { value: 'دهاقان', ostanId: 4 },
        { value: 'برف انبار', ostanId: 4 },
        { value: 'بادرود', ostanId: 4 },
        { value: 'کوهپایه', ostanId: 4 },
        { value: 'گلپایگان', ostanId: 4 },
        { value: 'عسگران', ostanId: 4 },
        { value: 'حنا', ostanId: 4 },
        { value: 'کهریزسنگ', ostanId: 4 },
        { value: 'مهاباد', ostanId: 4 },
        { value: 'کامو و چوگان', ostanId: 4 },
        { value: 'افوس', ostanId: 4 },
        { value: 'زیباشهر', ostanId: 4 },
        { value: 'کوشک', ostanId: 4 },
        { value: 'نایین', ostanId: 4 },
        { value: 'سین', ostanId: 4 },
        { value: 'زازران', ostanId: 4 },
        { value: 'مبارکه', ostanId: 4 },
        { value: 'ورزنه', ostanId: 4 },
        { value: 'ورنامخواست', ostanId: 4 },
        { value: 'شاپورآباد', ostanId: 4 },
        { value: 'فلاورجان', ostanId: 4 },
        { value: 'وزوان', ostanId: 4 },
        { value: 'اصفهان', ostanId: 4 },
        { value: 'باغ بهادران', ostanId: 4 },
        { value: 'باغ بهادران', ostanId: 4 },
        { value: 'دامنه', ostanId: 4 },
        { value: 'نطنز', ostanId: 4 },
        { value: 'محمدآباد', ostanId: 4 },
        { value: 'نیاسر', ostanId: 4 },
        { value: 'نوش آباد ', ostanId: 4 },
        { value: 'کمه', ostanId: 4 },
        { value: 'جوزدان', ostanId: 4 },
        { value: 'قمصر', ostanId: 4 },
        { value: 'جندق', ostanId: 4 },
        { value: 'طالخونچه', ostanId: 4 },
        { value: 'خمینی شهر', ostanId: 4 },
        { value: 'باغشاد', ostanId: 4 },
        { value: 'دستگرد', ostanId: 4 },
        { value: 'ابریشم', ostanId: 4 },
        { value: 'چهارباغ', ostanId: 5 },
        { value: 'آسارا', ostanId: 5 },
        { value: 'کرج', ostanId: 5 },
        { value: 'طالقان', ostanId: 5 },
        { value: 'هشتگرد', ostanId: 5 },
        { value: 'محمدشهر', ostanId: 5 },
        { value: 'مشکین دشت', ostanId: 5 },
        { value: 'نظرآباد', ostanId: 5 },
        { value: 'هشتگرد', ostanId: 5 },
        { value: 'ماهدشت', ostanId: 5 },
        { value: 'اشتهارد', ostanId: 5 },
        { value: 'کوهسار', ostanId: 5 },
        { value: 'گرمدره', ostanId: 5 },
        { value: 'تنکمان', ostanId: 5 },
        { value: 'گلسار', ostanId: 5 },
        { value: 'کمال شهر', ostanId: 5 },
        { value: 'فردیس', ostanId: 5 },
        { value: 'آبدانان', ostanId: 6 },
        { value: 'شباب', ostanId: 6 },
        { value: 'موسیان', ostanId: 6 },
        { value: 'بدره', ostanId: 6 },
        { value: 'ایلام', ostanId: 6 },
        { value: 'ایوان', ostanId: 6 },
        { value: 'مهران', ostanId: 6 },
        { value: 'آسمان آباد', ostanId: 6 },
        { value: 'پهله', ostanId: 6 },
        { value: 'مهر', ostanId: 6 },
        { value: 'سراب باغ', ostanId: 6 },
        { value: 'بلاوه', ostanId: 6 },
        { value: 'میمه', ostanId: 6 },
        { value: 'دره شهر', ostanId: 6 },
        { value: 'ارکواز', ostanId: 6 },
        { value: 'مورموری', ostanId: 6 },
        { value: 'توحید', ostanId: 6 },
        { value: 'دهلران', ostanId: 6 },
        { value: 'لومار', ostanId: 6 },
        { value: 'چوار', ostanId: 6 },
        { value: 'زرنه', ostanId: 6 },
        { value: 'صالح آباد', ostanId: 6 },
        { value: 'سرابله', ostanId: 6 },
        { value: 'ماژین', ostanId: 6 },
        { value: 'دلگشا', ostanId: 6 },
        { value: 'ریز', ostanId: 7 },
        { value: 'برازجان', ostanId: 7 },
        { value: 'بندرریگ', ostanId: 7 },
        { value: 'اهرم', ostanId: 7 },
        { value: 'دوراهک', ostanId: 7 },
        { value: 'خورموج', ostanId: 7 },
        { value: 'نخل تقی', ostanId: 7 },
        { value: 'کلمه', ostanId: 7 },
        { value: 'بندردیلم', ostanId: 7 },
        { value: 'وحدتیه', ostanId: 7 },
        { value: 'بنک', ostanId: 7 },
        { value: 'چغادک', ostanId: 7 },
        { value: 'بندردیر', ostanId: 7 },
        { value: 'کاکی', ostanId: 7 },
        { value: 'جم', ostanId: 7 },
        { value: 'دالکی', ostanId: 7 },
        { value: 'بندرگناوه', ostanId: 7 },
        { value: 'آباد', ostanId: 7 },
        { value: 'آبدان', ostanId: 7 },
        { value: 'خارک', ostanId: 7 },
        { value: 'شنبه', ostanId: 7 },
        { value: 'بوشکان', ostanId: 7 },
        { value: 'انارستان', ostanId: 7 },
        { value: 'شبانکاره', ostanId: 7 },
        { value: 'سیراف', ostanId: 7 },
        { value: 'دلوار', ostanId: 7 },
        { value: 'بردستان', ostanId: 7 },
        { value: 'بادوله', ostanId: 7 },
        { value: 'عسلویه', ostanId: 7 },
        { value: 'تنگ ارم', ostanId: 7 },
        { value: 'امام حسن', ostanId: 7 },
        { value: 'سعد آباد', ostanId: 7 },
        { value: 'بندرکنگان', ostanId: 7 },
        { value: 'بوشهر', ostanId: 7 },
        { value: 'بردخون', ostanId: 7 },
        { value: 'آب پخش', ostanId: 7 },
        { value: 'شاهدشهر', ostanId: 8 },
        { value: 'پیشوا', ostanId: 8 },
        { value: 'جوادآباد', ostanId: 8 },
        { value: 'ارجمند', ostanId: 8 },
        { value: 'ری', ostanId: 8 },
        { value: 'نصیرشهر', ostanId: 8 },
        { value: 'رودهن', ostanId: 8 },
        { value: 'اندیشه', ostanId: 8 },
        { value: 'نسیم شهر', ostanId: 8 },
        { value: 'صباشهر', ostanId: 8 },
        { value: 'ملارد', ostanId: 8 },
        { value: 'شمشک', ostanId: 8 },
        { value: 'پاکدشت', ostanId: 8 },
        { value: 'باقرشهر', ostanId: 8 },
        { value: 'احمد آباد مستوفی', ostanId: 8 },
        { value: 'کیلان', ostanId: 8 },
        { value: 'قرچک', ostanId: 8 },
        { value: 'فردوسیه', ostanId: 8 },
        { value: 'گلستان', ostanId: 8 },
        { value: 'کامو و ورامین', ostanId: 8 },
        { value: 'فیروزکوه', ostanId: 8 },
        { value: 'فشم', ostanId: 8 },
        { value: 'پرند', ostanId: 8 },
        { value: 'آبعلی', ostanId: 8 },
        { value: 'چهاردانگه', ostanId: 8 },
        { value: 'تهران', ostanId: 8 },
        { value: 'بومهن', ostanId: 8 },
        { value: 'وحیدیه', ostanId: 8 },
        { value: 'صفادشت', ostanId: 8 },
        { value: 'لواسان', ostanId: 8 },
        { value: 'فرون اباد', ostanId: 8 },
        { value: 'کهریزک', ostanId: 8 },
        { value: 'رباطکریم', ostanId: 8 },
        { value: 'آبسرد', ostanId: 8 },
        { value: 'باغستان', ostanId: 8 },
        { value: 'صالحیه', ostanId: 8 },
        { value: 'شهریار', ostanId: 8 },
        { value: 'قدس', ostanId: 8 },
        { value: 'تجریش', ostanId: 8 },
        { value: 'شریف آباد ', ostanId: 8 },
        { value: 'حسن آباد', ostanId: 8 },
        { value: 'اسلامشهر', ostanId: 8 },
        { value: 'دماوند', ostanId: 8 },
        { value: 'پردیس', ostanId: 8 },
        { value: 'وردنجان', ostanId: 9 },
        { value: 'گوجان ', ostanId: 9 },
        { value: 'گهرو', ostanId: 9 },
        { value: 'سورشجان', ostanId: 9 },
        { value: 'سرخون', ostanId: 9 },
        { value: 'شهرکرد', ostanId: 9 },
        { value: 'منج', ostanId: 9 },
        { value: 'بروجن', ostanId: 9 },
        { value: 'پردنجان', ostanId: 9 },
        { value: 'سامان', ostanId: 9 },
        { value: 'فرخ شهر', ostanId: 9 },
        { value: 'صمصامی', ostanId: 9 },
        { value: 'طاقانک', ostanId: 9 },
        { value: 'نقنه', ostanId: 9 },
        { value: 'لردگان', ostanId: 9 },
        { value: 'باباحیدر', ostanId: 9 },
        { value: 'دستنا', ostanId: 9 },
        { value: 'سودجان', ostanId: 9 },
        { value: 'بازفت', ostanId: 9 },
        { value: 'هفشجان', ostanId: 9 },
        { value: 'سردشت', ostanId: 9 },
        { value: 'فرادبنه', ostanId: 9 },
        { value: 'چلیچه', ostanId: 9 },
        { value: 'بن', ostanId: 9 },
        { value: 'فارسان', ostanId: 9 },
        { value: 'شلمزار', ostanId: 9 },
        { value: 'نافچ', ostanId: 9 },
        { value: 'دشتک', ostanId: 9 },
        { value: 'بلداجی', ostanId: 9 },
        { value: 'آلونی', ostanId: 9 },
        { value: 'گندمان', ostanId: 9 },
        { value: 'جونقان', ostanId: 9 },
        { value: 'ناغان', ostanId: 9 },
        { value: 'هارونی', ostanId: 9 },
        { value: 'چلگرد', ostanId: 9 },
        { value: 'کیان', ostanId: 9 },
        { value: 'اردل', ostanId: 9 },
        { value: 'سفیددشت', ostanId: 9 },
        { value: 'مال خلیفه', ostanId: 9 },
        { value: 'اسلامیه', ostanId: 10 },
        { value: 'شوسف', ostanId: 10 },
        { value: 'قاین', ostanId: 10 },
        { value: 'عشق آباد', ostanId: 10 },
        { value: 'طبس مسینا', ostanId: 10 },
        { value: 'ارسک', ostanId: 10 },
        { value: 'آیسک', ostanId: 10 },
        { value: 'نیمبلوک', ostanId: 10 },
        { value: 'دیهوک', ostanId: 10 },
        { value: 'سربیشه', ostanId: 10 },
        { value: 'محمدشهر', ostanId: 10 },
        { value: 'بیرجند', ostanId: 10 },
        { value: 'فردوس', ostanId: 10 },
        { value: 'نهبندان', ostanId: 10 },
        { value: 'اسفدن', ostanId: 10 },
        { value: 'گزیک', ostanId: 10 },
        { value: 'حاجی آباد', ostanId: 10 },
        { value: 'سه قلعه', ostanId: 10 },
        { value: 'آرین شهر', ostanId: 10 },
        { value: 'مود', ostanId: 10 },
        { value: 'خوسف', ostanId: 10 },
        { value: 'قهستان', ostanId: 10 },
        { value: 'بشرویه', ostanId: 10 },
        { value: 'سرایان', ostanId: 10 },
        { value: 'خضری دشت بیاض', ostanId: 10 },
        { value: 'طبس', ostanId: 10 },
        { value: 'اسدیه', ostanId: 10 },
        { value: 'زهان', ostanId: 10 },
        { value: 'بار', ostanId: 11 },
        { value: 'نیل شهر', ostanId: 11 },
        { value: 'جنگل', ostanId: 11 },
        { value: 'درود', ostanId: 11 },
        { value: 'رباط سنگ', ostanId: 11 },
        { value: 'سلطان آباد', ostanId: 11 },
        { value: 'فریمان', ostanId: 11 },
        { value: 'گناباد', ostanId: 11 },
        { value: 'کاریز', ostanId: 11 },
        { value: 'همت آباد', ostanId: 11 },
        { value: 'سلامی', ostanId: 11 },
        { value: 'باجگیران', ostanId: 11 },
        { value: 'بجستان', ostanId: 11 },
        { value: 'چناران', ostanId: 11 },
        { value: 'درگز', ostanId: 11 },
        { value: ' کلات', ostanId: 11 },
        { value: 'چکنه', ostanId: 11 },
        { value: 'نصرآباد', ostanId: 11 },
        { value: 'بردسکن', ostanId: 11 },
        { value: 'مشهد', ostanId: 11 },
        { value: 'کدکن', ostanId: 11 },
        { value: 'نقاب', ostanId: 11 },
        { value: 'قلندرآباد', ostanId: 11 },
        { value: 'کاشمر', ostanId: 11 },
        { value: 'شاندیز', ostanId: 11 },
        { value: 'نشتیفان', ostanId: 11 },
        { value: 'ششتمد', ostanId: 11 },
        { value: 'شادمهر', ostanId: 11 },
        { value: 'عشق آباد', ostanId: 4 },
        { value: 'چاپشلو', ostanId: 11 },
        { value: 'رشتخوار', ostanId: 11 },
        { value: 'قدمگاه', ostanId: 11 },
        { value: 'صالح آباد', ostanId: 11 },
        { value: 'داورزن', ostanId: 11 },
        { value: 'فرهادگرد', ostanId: 11 },
        { value: 'مشهدریزه', ostanId: 11 },
        { value: 'جغتای', ostanId: 11 },
        { value: 'مزدآوند', ostanId: 11 },
        { value: 'قوچان', ostanId: 11 },
        { value: 'یونسی', ostanId: 11 },
        { value: 'سنگان', ostanId: 11 },
        { value: 'نوخندان', ostanId: 11 },
        { value: 'کندر', ostanId: 11 },
        { value: 'نیشابور', ostanId: 11 },
        { value: 'احمدابادصولت', ostanId: 11 },
        { value: 'شهراباد', ostanId: 11 },
        { value: 'رضویه', ostanId: 11 },
        { value: 'تربت حیدریه', ostanId: 11 },
        { value: 'باخرز', ostanId: 11 },
        { value: ' سفیدسنگ', ostanId: 11 },
        { value: 'بیدخت', ostanId: 11 },
        { value: 'تایباد', ostanId: 11 },
        { value: 'فیروزه', ostanId: 11 },
        { value: 'قاسم آباد', ostanId: 11 },
        { value: 'سبزوار', ostanId: 11 },
        { value: 'فیض آباد', ostanId: 11 },
        { value: 'گلمکان', ostanId: 11 },
        { value: 'لطف آباد', ostanId: 11 },
        { value: 'شهرزو', ostanId: 11 },
        { value: 'خرو', ostanId: 11 },
        { value: 'تربت جام', ostanId: 11 },
        { value: 'انابد', ostanId: 11 },
        { value: 'ملک آباد', ostanId: 11 },
        { value: 'بایک', ostanId: 11 },
        { value: 'دولت آباد', ostanId: 11 },
        { value: 'سرخس', ostanId: 11 },
        { value: 'ریوش', ostanId: 11 },
        { value: 'طرقبه', ostanId: 11 },
        { value: 'خواف', ostanId: 11 },
        { value: 'روداب', ostanId: 11 },
        { value: 'خلیل آباد', ostanId: 11 },
        { value: 'چناران شهر', ostanId: 12 },
        { value: 'راز', ostanId: 12 },
        { value: 'پیش قلعه', ostanId: 12 },
        { value: 'قوشخانه', ostanId: 12 },
        { value: 'شوقان', ostanId: 12 },
        { value: 'اسفراین', ostanId: 12 },
        { value: 'گرمه', ostanId: 12 },
        { value: 'قاضی', ostanId: 12 },
        { value: 'شیروان', ostanId: 12 },
        { value: 'حصارگرمخان', ostanId: 12 },
        { value: 'آشخانه', ostanId: 12 },
        { value: 'تیتکانلو', ostanId: 12 },
        { value: 'جاجرم', ostanId: 12 },
        { value: 'بجنورد', ostanId: 12 },
        { value: 'درق', ostanId: 12 },
        { value: 'آوا', ostanId: 12 },
        { value: 'زیارت', ostanId: 12 },
        { value: 'سنخواست', ostanId: 12 },
        { value: 'صفی آباد', ostanId: 12 },
        { value: 'ایور', ostanId: 12 },
        { value: 'فاروج', ostanId: 12 },
        { value: 'لوجلی', ostanId: 12 },
        { value: 'هفتگل', ostanId: 13 },
        { value: 'بیدروبه', ostanId: 13 },
        { value: 'شاوور', ostanId: 13 },
        { value: 'حمزه', ostanId: 13 },
        { value: 'گتوند', ostanId: 13 },
        { value: 'شرافت', ostanId: 13 },
        { value: 'منصوریه', ostanId: 13 },
        { value: 'زهره', ostanId: 13 },
        { value: 'رامهرمز', ostanId: 13 },
        { value: 'بندرامام خمینی', ostanId: 13 },
        { value: 'کوت عبداله', ostanId: 13 },
        { value: 'میداود', ostanId: 13 },
        { value: 'چغامیش', ostanId: 13 },
        { value: 'ملاثانی', ostanId: 13 },
        { value: 'چم گلک', ostanId: 13 },
        { value: 'حر', ostanId: 13 },
        { value: 'شمس آباد', ostanId: 13 },
        { value: 'آبژدان', ostanId: 13 },
        { value: 'چویبده', ostanId: 13 },
        { value: 'مسجدسلیمان', ostanId: 13 },
        { value: 'مقاومت', ostanId: 13 },
        { value: 'ترکالکی', ostanId: 13 },
        { value: 'دارخوین', ostanId: 13 },
        { value: 'سردشت', ostanId: 13 },
        { value: 'لالی', ostanId: 13 },
        { value: 'کوت سیدنعیم', ostanId: 13 },
        { value: 'حمیدیه', ostanId: 13 },
        { value: 'دهدز', ostanId: 13 },
        { value: 'قلعه تل', ostanId: 13 },
        { value: 'میانرود', ostanId: 13 },
        { value: 'رفیع', ostanId: 13 },
        { value: 'اندیمشک', ostanId: 13 },
        { value: 'الوان', ostanId: 13 },
        { value: 'سالند', ostanId: 13 },
        { value: 'صالح شهر', ostanId: 13 },
        { value: 'اروندکنار', ostanId: 13 },
        { value: 'سرداران', ostanId: 13 },
        { value: 'تشان', ostanId: 13 },
        { value: 'رامشیر', ostanId: 13 },
        { value: 'شادگان', ostanId: 13 },
        { value: 'بندرماهشهر', ostanId: 13 },
        { value: 'جایزان', ostanId: 13 },
        { value: 'بستان', ostanId: 13 },
        { value: 'ویس', ostanId: 13 },
        { value: 'اهواز', ostanId: 13 },
        { value: 'فتح المبین', ostanId: 13 },
        { value: 'شهر امام', ostanId: 13 },
        { value: 'قلعه خواجه', ostanId: 13 },
        { value: 'حسینیه', ostanId: 13 },
        { value: 'گلگیر', ostanId: 13 },
        { value: 'مینوشهر', ostanId: 13 },
        { value: 'سماله', ostanId: 13 },
        { value: 'شوشتر', ostanId: 13 },
        { value: 'بهبهان', ostanId: 13 },
        { value: 'هندیجان', ostanId: 13 },
        { value: 'ابوحمیظه', ostanId: 13 },
        { value: 'آغاجاری', ostanId: 13 },
        { value: 'ایذه', ostanId: 13 },
        { value: 'صیدون', ostanId: 13 },
        { value: 'سیاه منصور', ostanId: 13 },
        { value: 'هویزه', ostanId: 13 },
        { value: 'آزادی', ostanId: 13 },
        { value: 'شوش', ostanId: 13 },
        { value: 'دزفول', ostanId: 13 },
        { value: 'جنت مکان', ostanId: 13 },
        { value: 'آبادان', ostanId: 13 },
        { value: 'گوریه', ostanId: 13 },
        { value: 'خرمشهر', ostanId: 13 },
        { value: 'مشراگه', ostanId: 13 },
        { value: 'خنافره', ostanId: 13 },
        { value: 'چمران', ostanId: 13 },
        { value: 'امیدیه', ostanId: 13 },
        { value: 'سوسنگرد', ostanId: 13 },
        { value: 'شیبان', ostanId: 13 },
        { value: 'الهایی', ostanId: 13 },
        { value: 'باغ ملک', ostanId: 13 },
        { value: 'صفی آباد', ostanId: 13 },
        { value: 'سجاس', ostanId: 14 },
        { value: 'زرین رود', ostanId: 14 },
        { value: 'آب بر', ostanId: 14 },
        { value: 'ارمغانخانه', ostanId: 14 },
        { value: 'کرسف', ostanId: 14 },
        { value: 'هیدج', ostanId: 14 },
        { value: 'سلطانیه', ostanId: 14 },
        { value: 'خرمدره', ostanId: 14 },
        { value: 'نیک پی', ostanId: 14 },
        { value: 'قیدار', ostanId: 14 },
        { value: 'ابهر', ostanId: 14 },
        { value: 'دندی', ostanId: 14 },
        { value: 'حلب ', ostanId: 14 },
        { value: 'نوربهار', ostanId: 14 },
        { value: 'گرماب', ostanId: 14 },
        { value: 'چورزق', ostanId: 14 },
        { value: 'زنجان', ostanId: 14 },
        { value: 'سهرورد', ostanId: 14 },
        { value: 'صایین قلعه', ostanId: 14 },
        { value: 'ماه نشان', ostanId: 14 },
        { value: 'زرین آباد', ostanId: 14 },
        { value: 'ایوانکی', ostanId: 15 },
        { value: 'مجن', ostanId: 15 },
        { value: 'دامغان', ostanId: 15 },
        { value: 'سرخه', ostanId: 15 },
        { value: 'مهدی شهر', ostanId: 15 },
        { value: 'شاهرود', ostanId: 15 },
        { value: 'سمنان', ostanId: 15 },
        { value: 'کهن آباد', ostanId: 15 },
        { value: 'گرمسار', ostanId: 15 },
        { value: 'کلاته خیج', ostanId: 15 },
        { value: 'دیباج', ostanId: 15 },
        { value: 'درجزین', ostanId: 15 },
        { value: 'رودیان', ostanId: 15 },
        { value: 'بسطام', ostanId: 15 },
        { value: 'امیریه', ostanId: 15 },
        { value: 'میامی', ostanId: 15 },
        { value: 'شهمیرزاد', ostanId: 15 },
        { value: 'بیارجمند', ostanId: 15 },
        { value: 'کلاته', ostanId: 15 },
        { value: 'آرادان', ostanId: 15 },
        { value: 'محمدی', ostanId: 16 },
        { value: 'شهرک علی اکبر', ostanId: 16 },
        { value: 'بنجار', ostanId: 16 },
        { value: 'گلمورتی', ostanId: 16 },
        { value: 'نگور', ostanId: 16 },
        { value: 'راسک', ostanId: 16 },
        { value: 'بنت', ostanId: 16 },
        { value: 'قصرقند', ostanId: 16 },
        { value: 'جالق', ostanId: 16 },
        { value: 'هیدوچ', ostanId: 16 },
        { value: 'نوک آباد', ostanId: 16 },
        { value: 'زهک', ostanId: 16 },
        { value: 'بمپور', ostanId: 16 },
        { value: 'پیشین', ostanId: 16 },
        { value: 'گشت', ostanId: 16 },
        { value: 'محمدآباد', ostanId: 16 },
        { value: 'زاهدان', ostanId: 16 },
        { value: 'زابلی', ostanId: 16 },
        { value: 'چاه بهار', ostanId: 16 },
        { value: 'زرآباد', ostanId: 16 },
        { value: 'بزمان', ostanId: 16 },
        { value: 'اسپکه', ostanId: 16 },
        { value: 'فنوج', ostanId: 16 },
        { value: 'سراوان', ostanId: 16 },
        { value: 'ادیمی', ostanId: 16 },
        { value: 'زابل', ostanId: 16 },
        { value: 'دوست محمد', ostanId: 16 },
        { value: 'ایرانشهر', ostanId: 16 },
        { value: 'سرباز', ostanId: 16 },
        { value: 'سیرکان', ostanId: 16 },
        { value: 'میرجاوه', ostanId: 16 },
        { value: 'نصرت آباد', ostanId: 16 },
        { value: 'سوران', ostanId: 16 },
        { value: 'خاش', ostanId: 16 },
        { value: 'کنارک', ostanId: 16 },
        { value: 'محمدان', ostanId: 16 },
        { value: 'نیک شهر', ostanId: 16 },
        { value: 'کازرون', ostanId: 17 },
        { value: 'کارزین (فتح آباد)', ostanId: 17 },
        { value: 'فدامی', ostanId: 17 },
        { value: 'خومه زار', ostanId: 17 },
        { value: 'سلطان شهر', ostanId: 17 },
        { value: 'فیروزآباد', ostanId: 17 },
        { value: 'دبیران', ostanId: 17 },
        { value: 'باب انار', ostanId: 17 },
        { value: 'رامجرد', ostanId: 17 },
        { value: 'سروستان', ostanId: 17 },
        { value: 'قره بلاغ', ostanId: 17 },
        { value: 'ارسنجان', ostanId: 17 },
        { value: 'دژکرد', ostanId: 17 },
        { value: 'بیرم', ostanId: 17 },
        { value: 'دهرم', ostanId: 17 },
        { value: 'شیراز', ostanId: 17 },
        { value: 'ایزدخواست', ostanId: 17 },
        { value: 'علامرودشت', ostanId: 17 },
        { value: 'اوز', ostanId: 17 },
        { value: 'وراوی', ostanId: 17 },
        { value: 'بیضا', ostanId: 17 },
        { value: 'نی ریز', ostanId: 17 },
        { value: 'کنارتخته', ostanId: 17 },
        { value: 'امام شهر', ostanId: 17 },
        { value: 'جهرم', ostanId: 17 },
        { value: 'بابامنیر', ostanId: 17 },
        { value: 'گراش', ostanId: 17 },
        { value: 'فسا', ostanId: 17 },
        { value: 'شهرپیر', ostanId: 17 },
        { value: 'حسن اباد', ostanId: 17 },
        { value: 'کامفیروز', ostanId: 17 },
        { value: 'خنج', ostanId: 17 },
        { value: 'خانه زنیان', ostanId: 17 },
        { value: 'استهبان', ostanId: 17 },
        { value: 'بوانات', ostanId: 17 },
        { value: 'لطیفی', ostanId: 17 },
        { value: 'فراشبند', ostanId: 17 },
        { value: 'زرقان', ostanId: 17 },
        { value: 'صغاد', ostanId: 17 },
        { value: 'اشکنان', ostanId: 17 },
        { value: 'قایمیه', ostanId: 17 },
        { value: 'گله دار', ostanId: 17 },
        { value: 'دوبرجی', ostanId: 17 },
        { value: 'آباده طشک', ostanId: 17 },
        { value: 'خرامه', ostanId: 17 },
        { value: 'میمند', ostanId: 17 },
        { value: 'افزر', ostanId: 17 },
        { value: 'دوزه', ostanId: 17 },
        { value: 'سیدان', ostanId: 17 },
        { value: 'کوپن', ostanId: 17 },
        { value: 'زاهدشهر', ostanId: 17 },
        { value: 'قادراباد', ostanId: 17 },
        { value: 'سده', ostanId: 17 },
        { value: 'بنارویه', ostanId: 17 },
        { value: 'سعادت شهر', ostanId: 17 },
        { value: 'شهرصدرا', ostanId: 17 },
        { value: 'سورمق', ostanId: 17 },
        { value: 'حسامی', ostanId: 17 },
        { value: 'خوزی', ostanId: 17 },
        { value: 'اردکان', ostanId: 17 },
        { value: 'قطرویه', ostanId: 17 },
        { value: 'نودان', ostanId: 17 },
        { value: 'مبارک آباددیز', ostanId: 17 },
        { value: 'داراب', ostanId: 17 },
        { value: 'نورآباد', ostanId: 17 },
        { value: 'کوار', ostanId: 17 },
        { value: 'نوبندگان', ostanId: 17 },
        { value: 'حاجی آباد', ostanId: 17 },
        { value: 'خاوران', ostanId: 17 },
        { value: 'مرودشت', ostanId: 17 },
        { value: 'کوهنجان', ostanId: 17 },
        { value: 'ششده', ostanId: 17 },
        { value: 'مزایجان', ostanId: 17 },
        { value: 'ایج', ostanId: 17 },
        { value: 'خور', ostanId: 17 },
        { value: 'نوجین', ostanId: 17 },
        { value: 'لپویی', ostanId: 17 },
        { value: 'بهمن', ostanId: 17 },
        { value: 'اهل', ostanId: 17 },
        { value: 'خشت', ostanId: 17 },
        { value: 'مهر', ostanId: 17 },
        { value: 'جنت شهر', ostanId: 17 },
        { value: 'مشکان', ostanId: 17 },
        { value: 'بالاده', ostanId: 17 },
        { value: 'قیر', ostanId: 17 },
        { value: 'قطب آباد', ostanId: 17 },
        { value: 'خانیمن', ostanId: 17 },
        { value: 'مصیری', ostanId: 17 },
        { value: 'میانشهر', ostanId: 17 },
        { value: 'صفاشهر', ostanId: 17 },
        { value: 'اقلید', ostanId: 17 },
        { value: 'عمادده', ostanId: 17 },
        { value: 'مادرسلیمان', ostanId: 17 },
        { value: 'داریان', ostanId: 17 },
        { value: 'رونیز', ostanId: 17 },
        { value: 'کره ای', ostanId: 17 },
        { value: 'لار', ostanId: 17 },
        { value: 'اسیر', ostanId: 17 },
        { value: 'هماشهر', ostanId: 17 },
        { value: 'آباده', ostanId: 17 },
        { value: 'لامرد', ostanId: 17 },
        { value: 'سگزآباد', ostanId: 18 },
        { value: 'بیدستان', ostanId: 18 },
        { value: 'کوهین', ostanId: 18 },
        { value: 'رازمیان', ostanId: 18 },
        { value: 'خرمدشت', ostanId: 18 },
        { value: 'آبگرم', ostanId: 18 },
        { value: 'شال', ostanId: 18 },
        { value: 'شریفیه', ostanId: 18 },
        { value: 'اقبالیه', ostanId: 18 },
        { value: 'نرجه', ostanId: 18 },
        { value: 'ارداق', ostanId: 18 },
        { value: 'الوند', ostanId: 18 },
        { value: 'خاکعلی', ostanId: 18 },
        { value: 'سیردان', ostanId: 18 },
        { value: 'ضیاڈآباد', ostanId: 18 },
        { value: 'بویین زهرا', ostanId: 18 },
        { value: 'محمدیه', ostanId: 18 },
        { value: 'محمودآبادنمونه', ostanId: 18 },
        { value: 'معلم کلایه', ostanId: 18 },
        { value: 'اسفرورین', ostanId: 18 },
        { value: 'آوج', ostanId: 18 },
        { value: 'دانسفهان', ostanId: 18 },
        { value: 'آبیک', ostanId: 18 },
        { value: 'قزوین', ostanId: 18 },
        { value: 'تاکستان', ostanId: 18 },
        { value: 'کهک', ostanId: 19 },
        { value: 'قم', ostanId: 19 },
        { value: 'سلفچگان', ostanId: 19 },
        { value: 'جعفریه', ostanId: 19 },
        { value: 'قنوات', ostanId: 19 },
        { value: 'دستجرد', ostanId: 19 },
        { value: 'قروه', ostanId: 20 },
        { value: 'توپ آغاج', ostanId: 20 },
        { value: 'سروآباد', ostanId: 20 },
        { value: 'بویین سفلی', ostanId: 20 },
        { value: 'زرینه', ostanId: 20 },
        { value: 'دلبران', ostanId: 20 },
        { value: 'سنندج', ostanId: 20 },
        { value: 'یاسوکند', ostanId: 20 },
        { value: 'موچش', ostanId: 20 },
        { value: 'بانه', ostanId: 20 },
        { value: 'مریوان', ostanId: 20 },
        { value: 'سریش آباد', ostanId: 20 },
        { value: 'صاحب', ostanId: 20 },
        { value: 'دهگلان', ostanId: 20 },
        { value: 'بابارشانی', ostanId: 20 },
        { value: 'دیواندره', ostanId: 20 },
        { value: 'برده رشه', ostanId: 20 },
        { value: 'شویشه', ostanId: 20 },
        { value: 'بیجار', ostanId: 20 },
        { value: 'اورامان تخت', ostanId: 20 },
        { value: 'کانی سور', ostanId: 20 },
        { value: 'کانی دینار', ostanId: 20 },
        { value: 'دزج', ostanId: 20 },
        { value: 'سقز', ostanId: 20 },
        { value: 'بلبان آباد', ostanId: 20 },
        { value: 'پیرتاج', ostanId: 20 },
        { value: 'کامیاران', ostanId: 20 },
        { value: 'آرمرده', ostanId: 20 },
        { value: 'چناره', ostanId: 20 },
        { value: 'کهنوج', ostanId: 21 },
        { value: 'بلوک', ostanId: 21 },
        { value: 'پاریز', ostanId: 21 },
        { value: 'گنبکی', ostanId: 21 },
        { value: 'زنگی آباد', ostanId: 21 },
        { value: 'بم', ostanId: 21 },
        { value: 'خانوک', ostanId: 21 },
        { value: 'کیانشهر', ostanId: 21 },
        { value: 'جوپار', ostanId: 21 },
        { value: 'عنبرآباد', ostanId: 21 },
        { value: 'جوزم', ostanId: 21 },
        { value: 'نظام شهر', ostanId: 21 },
        { value: 'لاله زار', ostanId: 21 },
        { value: 'کشکوییه', ostanId: 21 },
        { value: 'زیدآباد', ostanId: 21 },
        { value: 'هنزا', ostanId: 21 },
        { value: 'چترود', ostanId: 21 },
        { value: 'جبالبارز', ostanId: 21 },
        { value: 'سیرجان', ostanId: 21 },
        { value: 'رودبار', ostanId: 21 },
        { value: 'کرمان', ostanId: 21 },
        { value: 'بافت', ostanId: 21 },
        { value: 'صفاییه', ostanId: 21 },
        { value: 'منوجان', ostanId: 21 },
        { value: 'اندوهجرد', ostanId: 21 },
        { value: 'هجدک', ostanId: 21 },
        { value: 'خورسند', ostanId: 21 },
        { value: 'امین شهر', ostanId: 21 },
        { value: 'بردسیر', ostanId: 21 },
        { value: 'رفسنجان', ostanId: 21 },
        { value: 'هماشهر', ostanId: 21 },
        { value: 'محمدآباد', ostanId: 21 },
        { value: 'اختیارآباد', ostanId: 21 },
        { value: 'بروات', ostanId: 21 },
        { value: 'ریحان', ostanId: 21 },
        { value: 'کوهبنان', ostanId: 21 },
        { value: 'ماهان', ostanId: 21 },
        { value: 'دوساری', ostanId: 21 },
        { value: 'دهج', ostanId: 21 },
        { value: 'فاریاب', ostanId: 21 },
        { value: 'گلزار', ostanId: 21 },
        { value: 'بهرمان', ostanId: 21 },
        { value: 'بلورد', ostanId: 21 },
        { value: 'فهرج', ostanId: 21 },
        { value: 'کاظم آباد', ostanId: 21 },
        { value: 'جیرفت', ostanId: 21 },
        { value: 'نجف شهر', ostanId: 21 },
        { value: 'قلعه گنج', ostanId: 21 },
        { value: 'باغین', ostanId: 21 },
        { value: 'بزنجان', ostanId: 21 },
        { value: 'زرند', ostanId: 21 },
        { value: 'نودژ', ostanId: 21 },
        { value: 'گلباف', ostanId: 21 },
        { value: 'راور', ostanId: 21 },
        { value: 'خاتون اباد', ostanId: 21 },
        { value: 'نرماشیر', ostanId: 21 },
        { value: 'دشتکار', ostanId: 21 },
        { value: 'مس سرچشمه', ostanId: 21 },
        { value: 'خواجو شهر', ostanId: 21 },
        { value: 'رابر', ostanId: 21 },
        { value: 'راین', ostanId: 21 },
        { value: 'درب بهشت', ostanId: 21 },
        { value: 'یزدان شهر', ostanId: 21 },
        { value: 'زهکلوت', ostanId: 21 },
        { value: 'محی آباد', ostanId: 21 },
        { value: 'مردهک', ostanId: 21 },
        { value: 'شهداد', ostanId: 21 },
        { value: 'ارزوییه', ostanId: 21 },
        { value: 'نگار', ostanId: 21 },
        { value: 'شهربابک', ostanId: 21 },
        { value: 'انار', ostanId: 21 },
        { value: 'سنقر', ostanId: 22 },
        { value: 'شاهو', ostanId: 22 },
        { value: 'تازه آباد', ostanId: 22 },
        { value: 'هلشی', ostanId: 22 },
        { value: 'جوانرود', ostanId: 22 },
        { value: 'قصرشیرین', ostanId: 22 },
        { value: 'نوسود', ostanId: 22 },
        { value: 'کرند', ostanId: 22 },
        { value: 'کوزران', ostanId: 22 },
        { value: 'بیستون', ostanId: 22 },
        { value: 'حمیل', ostanId: 22 },
        { value: 'گیلانغرب', ostanId: 22 },
        { value: 'سطر', ostanId: 22 },
        { value: 'روانسر', ostanId: 22 },
        { value: 'پاوه', ostanId: 22 },
        { value: 'ازگله', ostanId: 22 },
        { value: 'کرمانشاه', ostanId: 22 },
        { value: 'میان راهان', ostanId: 22 },
        { value: 'کنگاور', ostanId: 22 },
        { value: 'سرپل ذهاب', ostanId: 22 },
        { value: 'ریجاب', ostanId: 22 },
        { value: 'باینگان', ostanId: 22 },
        { value: 'هرسین', ostanId: 22 },
        { value: 'اسلام آبادغرب', ostanId: 22 },
        { value: 'سرمست', ostanId: 22 },
        { value: 'سومار', ostanId: 22 },
        { value: 'نودشه', ostanId: 22 },
        { value: 'گهواره', ostanId: 22 },
        { value: 'رباط', ostanId: 22 },
        { value: 'صحنه', ostanId: 22 },
        { value: 'گودین', ostanId: 22 },
        { value: 'گراب سفلی', ostanId: 23 },
        { value: 'لنده', ostanId: 23 },
        { value: 'سی سخت', ostanId: 23 },
        { value: 'دهدشت', ostanId: 23 },
        { value: 'یاسوج', ostanId: 23 },
        { value: 'سرفاریاب', ostanId: 23 },
        { value: 'دوگنبدان', ostanId: 23 },
        { value: 'چیتاب', ostanId: 23 },
        { value: 'لیکک', ostanId: 23 },
        { value: 'دیشموک', ostanId: 23 },
        { value: 'مادوان', ostanId: 23 },
        { value: 'باشت', ostanId: 23 },
        { value: 'پاتاوه', ostanId: 23 },
        { value: 'قلعه رییسی', ostanId: 23 },
        { value: 'مارگون', ostanId: 23 },
        { value: 'چرام', ostanId: 23 },
        { value: 'سوق', ostanId: 23 },
        { value: 'سیمین شهر', ostanId: 24 },
        { value: 'مزرعه', ostanId: 24 },
        { value: 'رامیان', ostanId: 24 },
        { value: 'فراغی', ostanId: 24 },
        { value: 'گنبدکاووس', ostanId: 24 },
        { value: 'کردکوی', ostanId: 24 },
        { value: 'مراوه', ostanId: 24 },
        { value: 'بندرترکمن', ostanId: 24 },
        { value: 'نگین شهر', ostanId: 24 },
        { value: 'آق قلا', ostanId: 24 },
        { value: 'سرخنکلاته', ostanId: 24 },
        { value: 'گالیکش', ostanId: 24 },
        { value: 'سنگدوین', ostanId: 24 },
        { value: 'دلند', ostanId: 24 },
        { value: 'بندرگز', ostanId: 24 },
        { value: 'نوده خاندوز', ostanId: 24 },
        { value: 'مینودشت', ostanId: 24 },
        { value: 'گرگان', ostanId: 24 },
        { value: 'گمیش تپه', ostanId: 24 },
        { value: 'علی اباد', ostanId: 24 },
        { value: 'خان ببین', ostanId: 24 },
        { value: 'کلاله', ostanId: 24 },
        { value: 'اینچه برون', ostanId: 24 },
        { value: 'فاضل آباد', ostanId: 24 },
        { value: 'تاتارعلیا', ostanId: 24 },
        { value: 'نوکنده', ostanId: 24 },
        { value: 'آزادشهر', ostanId: 24 },
        { value: 'انبارآلوم', ostanId: 24 },
        { value: 'جلین', ostanId: 24 },
        { value: 'منجیل', ostanId: 25 },
        { value: 'شلمان', ostanId: 25 },
        { value: 'خشکبیجار', ostanId: 25 },
        { value: 'ماکلوان', ostanId: 25 },
        { value: 'سنگر', ostanId: 25 },
        { value: 'مرجقل', ostanId: 25 },
        { value: 'لیسار', ostanId: 25 },
        { value: 'رضوانشهر', ostanId: 25 },
        { value: 'رحیم آباد', ostanId: 25 },
        { value: 'لوندویل', ostanId: 25 },
        { value: 'احمدسرگوراب', ostanId: 25 },
        { value: 'لوشان', ostanId: 25 },
        { value: 'اطاقور', ostanId: 25 },
        { value: 'لشت نشاء', ostanId: 25 },
        { value: 'فومن', ostanId: 25 },
        { value: 'چوبر', ostanId: 25 },
        { value: 'بازار جمعه', ostanId: 25 },
        { value: 'کلاچای', ostanId: 25 },
        { value: 'بندرانزلی', ostanId: 25 },
        { value: 'املش', ostanId: 25 },
        { value: 'رستم آباد', ostanId: 25 },
        { value: 'لاهیجان', ostanId: 25 },
        { value: 'توتکابن', ostanId: 25 },
        { value: 'لنگرود', ostanId: 25 },
        { value: 'کوچصفهان', ostanId: 25 },
        { value: 'صومعه سرا', ostanId: 25 },
        { value: 'اسالم', ostanId: 25 },
        { value: 'دیلمان', ostanId: 25 },
        { value: 'رودسر', ostanId: 25 },
        { value: 'کیاشهر', ostanId: 25 },
        { value: 'شفت', ostanId: 25 },
        { value: 'رودبار', ostanId: 25 },
        { value: 'کومله', ostanId: 25 },
        { value: 'رشت', ostanId: 25 },
        { value: 'ماسوله', ostanId: 25 },
        { value: 'خمام', ostanId: 25 },
        { value: 'ماسال', ostanId: 25 },
        { value: 'واجارگاه', ostanId: 25 },
        { value: 'هشتپر (تالش)', ostanId: 25 },
        { value: 'پره سر', ostanId: 25 },
        { value: 'بره سر', ostanId: 25 },
        { value: 'آستارا', ostanId: 25 },
        { value: 'رودبنه', ostanId: 25 },
        { value: 'جیرنده', ostanId: 25 },
        { value: 'چاف و چمخاله', ostanId: 25 },
        { value: 'لولمان', ostanId: 25 },
        { value: 'گوراب زرمیخ', ostanId: 25 },
        { value: 'حویق', ostanId: 25 },
        { value: 'سیاهکل', ostanId: 25 },
        { value: 'چابکسر', ostanId: 25 },
        { value: 'آستانه اشرفیه', ostanId: 25 },
        { value: 'رانکوه', ostanId: 25 },
        { value: 'چالانچولان', ostanId: 26 },
        { value: 'بیران شهر', ostanId: 26 },
        { value: 'ویسیان', ostanId: 26 },
        { value: 'شول آباد', ostanId: 26 },
        { value: 'پلدختر', ostanId: 26 },
        { value: 'کوهدشت', ostanId: 26 },
        { value: 'هفت چشمه', ostanId: 26 },
        { value: 'بروجرد', ostanId: 26 },
        { value: 'الشتر', ostanId: 26 },
        { value: 'مومن آباد', ostanId: 26 },
        { value: 'دورود', ostanId: 26 },
        { value: 'زاغه', ostanId: 26 },
        { value: 'چقابل', ostanId: 26 },
        { value: 'الیگودرز', ostanId: 26 },
        { value: 'معمولان', ostanId: 26 },
        { value: 'کوهنانی', ostanId: 26 },
        { value: 'نورآباد', ostanId: 26 },
        { value: 'سپیددشت', ostanId: 26 },
        { value: 'سراب دوره', ostanId: 26 },
        { value: 'ازنا', ostanId: 26 },
        { value: 'گراب', ostanId: 26 },
        { value: 'خرم آباد', ostanId: 26 },
        { value: 'اشترینان', ostanId: 26 },
        { value: 'فیروزآباد', ostanId: 26 },
        { value: 'درب گنبد', ostanId: 26 },
        { value: 'گلوگاه', ostanId: 27 },
        { value: 'پل سفید', ostanId: 27 },
        { value: 'دابودشت', ostanId: 27 },
        { value: 'چالوس', ostanId: 27 },
        { value: 'کیاسر', ostanId: 27 },
        { value: 'بهنمیر', ostanId: 27 },
        { value: 'تنکابن', ostanId: 27 },
        { value: 'کلاردشت', ostanId: 27 },
        { value: 'ایزدشهر', ostanId: 27 },
        { value: 'گتاب', ostanId: 27 },
        { value: 'سلمان شهر', ostanId: 27 },
        { value: 'ارطه', ostanId: 27 },
        { value: 'امیرکلا', ostanId: 27 },
        { value: 'کوهی خیل', ostanId: 27 },
        { value: 'پایین هولار', ostanId: 27 },
        { value: 'گزنک', ostanId: 27 },
        { value: 'محمودآباد', ostanId: 27 },
        { value: 'رامسر', ostanId: 27 },
        { value: 'نوشهر', ostanId: 27 },
        { value: 'خلیل شهر', ostanId: 27 },
        { value: 'کیاکلا', ostanId: 27 },
        { value: 'نور', ostanId: 27 },
        { value: 'مرزیکلا', ostanId: 27 },
        { value: 'فریدونکنار', ostanId: 27 },
        { value: 'زیرآب', ostanId: 27 },
        { value: 'امامزاده عبدالله', ostanId: 27 },
        { value: 'هچیرود', ostanId: 27 },
        { value: 'فریم', ostanId: 27 },
        { value: 'هادی شهر', ostanId: 27 },
        { value: 'نشتارود', ostanId: 27 },
        { value: 'پول', ostanId: 27 },
        { value: 'بهشهر', ostanId: 27 },
        { value: 'کلارآباد', ostanId: 27 },
        { value: 'بلده', ostanId: 27 },
        { value: 'بابل', ostanId: 27 },
        { value: 'جویبار', ostanId: 27 },
        { value: 'آلاشت', ostanId: 27 },
        { value: 'آمل', ostanId: 27 },
        { value: 'نکا', ostanId: 27 },
        { value: 'کتالم وسادات شهر', ostanId: 27 },
        { value: 'بابلسر', ostanId: 27 },
        { value: 'شیرود', ostanId: 27 },
        { value: 'شیرگاه', ostanId: 27 },
        { value: 'رویان', ostanId: 27 },
        { value: 'زرگرمحله', ostanId: 27 },
        { value: 'عباس اباد', ostanId: 27 },
        { value: 'قایم شهر', ostanId: 27 },
        { value: 'خوش رودپی', ostanId: 27 },
        { value: 'مرزن آباد', ostanId: 27 },
        { value: 'ساری', ostanId: 27 },
        { value: 'رینه', ostanId: 27 },
        { value: 'سرخرود', ostanId: 27 },
        { value: 'خرم آباد', ostanId: 27 },
        { value: 'کجور', ostanId: 27 },
        { value: 'رستمکلا', ostanId: 27 },
        { value: 'سورک', ostanId: 27 },
        { value: 'چمستان', ostanId: 27 },
        { value: 'آستانه', ostanId: 28 },
        { value: 'خنجین', ostanId: 28 },
        { value: 'نراق', ostanId: 28 },
        { value: 'کمیجان', ostanId: 28 },
        { value: 'آشتیان', ostanId: 28 },
        { value: 'رازقان', ostanId: 28 },
        { value: 'مهاجران', ostanId: 28 },
        { value: 'غرق آباد', ostanId: 28 },
        { value: 'خنداب', ostanId: 28 },
        { value: 'قورچی باشی', ostanId: 28 },
        { value: 'خشکرود', ostanId: 28 },
        { value: 'ساروق', ostanId: 28 },
        { value: 'محلات', ostanId: 28 },
        { value: 'شازند', ostanId: 28 },
        { value: 'ساوه', ostanId: 28 },
        { value: 'میلاجرد', ostanId: 28 },
        { value: 'تفرش', ostanId: 28 },
        { value: 'زاویه', ostanId: 28 },
        { value: 'اراک', ostanId: 28 },
        { value: 'توره', ostanId: 28 },
        { value: 'نوبران', ostanId: 28 },
        { value: 'فرمهین', ostanId: 28 },
        { value: 'دلیجان', ostanId: 28 },
        { value: 'پرندک', ostanId: 28 },
        { value: 'کارچان', ostanId: 28 },
        { value: 'نیمور', ostanId: 28 },
        { value: 'هندودر', ostanId: 28 },
        { value: 'آوه', ostanId: 28 },
        { value: 'جاورسیان', ostanId: 28 },
        { value: 'خمین', ostanId: 28 },
        { value: 'مامونیه', ostanId: 28 },
        { value: 'داودآباد', ostanId: 28 },
        { value: 'شهباز', ostanId: 28 },
        { value: 'بیکاء', ostanId: 29 },
        { value: 'تیرور', ostanId: 29 },
        { value: 'گروک', ostanId: 29 },
        { value: 'قشم', ostanId: 29 },
        { value: 'کوشکنار', ostanId: 29 },
        { value: 'کیش', ostanId: 29 },
        { value: 'سرگز', ostanId: 29 },
        { value: 'بندرعباس', ostanId: 29 },
        { value: 'زیارتعلی', ostanId: 29 },
        { value: 'سندرک', ostanId: 29 },
        { value: 'کوهستک', ostanId: 29 },
        { value: 'لمزان', ostanId: 29 },
        { value: 'رویدر', ostanId: 29 },
        { value: 'قلعه قاضی', ostanId: 29 },
        { value: 'فارغان', ostanId: 29 },
        { value: 'ابوموسی', ostanId: 29 },
        { value: 'هشتبندی', ostanId: 29 },
        { value: 'سردشت', ostanId: 29 },
        { value: 'درگهان', ostanId: 29 },
        { value: 'پارسیان', ostanId: 29 },
        { value: 'کنگ', ostanId: 29 },
        { value: 'جناح', ostanId: 29 },
        { value: 'تازیان پایین', ostanId: 29 },
        { value: 'دهبارز', ostanId: 29 },
        { value: 'میناب', ostanId: 29 },
        { value: 'سیریک', ostanId: 29 },
        { value: 'سوزا', ostanId: 29 },
        { value: 'خمیر', ostanId: 29 },
        { value: 'چارک', ostanId: 29 },
        { value: 'حاجی اباد', ostanId: 29 },
        { value: 'فین', ostanId: 29 },
        { value: 'بندرجاسک', ostanId: 29 },
        { value: 'گوهران', ostanId: 29 },
        { value: 'هرمز', ostanId: 29 },
        { value: 'دشتی', ostanId: 29 },
        { value: 'بندرلنگه', ostanId: 29 },
        { value: 'بستک', ostanId: 29 },
        { value: 'تخت', ostanId: 29 },
        { value: 'زنگنه', ostanId: 30 },
        { value: 'دمق', ostanId: 30 },
        { value: 'سرکان', ostanId: 30 },
        { value: 'آجین', ostanId: 30 },
        { value: 'جورقان', ostanId: 30 },
        { value: 'برزول', ostanId: 30 },
        { value: 'فامنین', ostanId: 30 },
        { value: 'سامن', ostanId: 30 },
        { value: 'بهار', ostanId: 30 },
        { value: 'فرسفج', ostanId: 30 },
        { value: 'شیرین سو', ostanId: 30 },
        { value: 'مریانج', ostanId: 30 },
        { value: 'فیروزان', ostanId: 30 },
        { value: 'قروه درجزین', ostanId: 30 },
        { value: 'ازندریان', ostanId: 30 },
        { value: 'لالجین', ostanId: 30 },
        { value: 'گل تپه', ostanId: 30 },
        { value: 'گیان', ostanId: 30 },
        { value: 'ملایر', ostanId: 30 },
        { value: 'صالح آباد', ostanId: 30 },
        { value: 'تویسرکان', ostanId: 30 },
        { value: 'اسدآباد', ostanId: 30 },
        { value: 'همدان', ostanId: 30 },
        { value: 'نهاوند', ostanId: 30 },
        { value: 'رزن', ostanId: 30 },
        { value: 'جوکار', ostanId: 30 },
        { value: 'مهاجران', ostanId: 30 },
        { value: 'کبودرآهنگ', ostanId: 30 },
        { value: 'قهاوند', ostanId: 30 },
        { value: 'مروست', ostanId: 31 },
        { value: 'مهردشت', ostanId: 31 },
        { value: 'حمیدیا', ostanId: 31 },
        { value: 'تفت', ostanId: 31 },
        { value: 'اشکذر', ostanId: 31 },
        { value: 'ندوشن', ostanId: 31 },
        { value: 'یزد', ostanId: 31 },
        { value: 'عقدا', ostanId: 31 },
        { value: 'بهاباد', ostanId: 31 },
        { value: 'ابرکوه', ostanId: 31 },
        { value: 'زارچ', ostanId: 31 },
        { value: 'نیر', ostanId: 31 },
        { value: 'اردکان', ostanId: 31 },
        { value: 'هرات', ostanId: 31 },
        { value: 'بفروییه', ostanId: 31 },
        { value: 'شاهدیه', ostanId: 31 },
        { value: 'بافق', ostanId: 31 },
        { value: 'خضرآباد', ostanId: 31 },
        { value: 'میبد', ostanId: 31 },
        { value: 'مهریز', ostanId: 31 },
        { value: 'احمدآباد', ostanId: 31 },


    ]
